# Generated by Django 5.2.6 on 2025-09-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('read_write', 'Read & Write'), ('read_only', 'Read Only')], default='admin', max_length=20),
        ),
    ]
